services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=postgres://user:password@postgres:5432/rankings?sslmode=disable
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rankings
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d rankings"]
      interval: 2s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
