// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: espn_sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const syncDeletePlayer = `-- name: SyncDeletePlayer :exec
DELETE FROM players WHERE id = $1
`

func (q *Queries) SyncDeletePlayer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, syncDeletePlayer, id)
	return err
}

const syncInsertPlayer = `-- name: SyncInsertPlayer :exec
INSERT INTO players (drafted_by_username, player_name, position, team, drafted_at)
VALUES ($1, $2, $3, $4, $5)
`

type SyncInsertPlayerParams struct {
	DraftedByUsername pgtype.Text
	PlayerName        string
	Position          string
	Team              string
	DraftedAt         int32
}

func (q *Queries) SyncInsertPlayer(ctx context.Context, arg SyncInsertPlayerParams) error {
	_, err := q.db.Exec(ctx, syncInsertPlayer,
		arg.DraftedByUsername,
		arg.PlayerName,
		arg.Position,
		arg.Team,
		arg.DraftedAt,
	)
	return err
}

const syncListPlayers = `-- name: SyncListPlayers :many
SELECT id, drafted_by_username, player_name, position, team, drafted_at
FROM players
ORDER BY id
`

type SyncListPlayersRow struct {
	ID                int64
	DraftedByUsername pgtype.Text
	PlayerName        string
	Position          string
	Team              string
	DraftedAt         int32
}

func (q *Queries) SyncListPlayers(ctx context.Context) ([]SyncListPlayersRow, error) {
	rows, err := q.db.Query(ctx, syncListPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncListPlayersRow
	for rows.Next() {
		var i SyncListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.DraftedByUsername,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.DraftedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncReferencedPlayerIDs = `-- name: SyncReferencedPlayerIDs :many
SELECT DISTINCT player_id FROM rankings
`

func (q *Queries) SyncReferencedPlayerIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, syncReferencedPlayerIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var player_id int64
		if err := rows.Scan(&player_id); err != nil {
			return nil, err
		}
		items = append(items, player_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncUpdatePlayer = `-- name: SyncUpdatePlayer :exec
UPDATE players
SET drafted_by_username = $1,
    player_name = $2,
    position = $3,
    team = $4,
    drafted_at = $5
WHERE id = $6
`

type SyncUpdatePlayerParams struct {
	DraftedByUsername pgtype.Text
	PlayerName        string
	Position          string
	Team              string
	DraftedAt         int32
	ID                int64
}

func (q *Queries) SyncUpdatePlayer(ctx context.Context, arg SyncUpdatePlayerParams) error {
	_, err := q.db.Exec(ctx, syncUpdatePlayer,
		arg.DraftedByUsername,
		arg.PlayerName,
		arg.Position,
		arg.Team,
		arg.DraftedAt,
		arg.ID,
	)
	return err
}
