// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	ID                int64
	DraftedByUsername pgtype.Text
	PlayerName        string
	Position          string
	Team              string
	DraftedAt         int32
	CreatedAt         pgtype.Timestamptz
}

type Ranking struct {
	ID        int64
	Owner     string
	Rank      int32
	CreatedAt pgtype.Timestamptz
	PlayerID  int64
}

type Session struct {
	Token     string
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
}
