// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ranking struct {
	ID         int64
	Owner      string
	PlayerName string
	Rank       int32
	CreatedAt  pgtype.Timestamptz
}
