// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	ID                int64
	DraftedByUsername pgtype.Text
	PlayerName        string
	Position          string
	Team              string
	DraftedAt         int32
	CreatedAt         pgtype.Timestamptz
}

type Ranking struct {
	ID        int64
	Owner     string
	Rank      int32
	CreatedAt pgtype.Timestamptz
	PlayerID  int64
}

type RankingSnapshot struct {
	ID         int64
	TakenAt    pgtype.Timestamptz
	Owner      string
	PlayerID   int64
	Rank       int32
	OwnerTotal int32
}

type Session struct {
	Token     string
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type SyncLog struct {
	ID                 int64
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
	Source             string
	Status             string
	Message            pgtype.Text
	Inserted           int32
	Updated            int32
	Deleted            int32
	Unchanged          int32
	DeleteSkippedCount int32
}

type TierBreak struct {
	ID         int64
	Owner      string
	Position   string
	BeforeRank int32
	Label      pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
}
