// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
)

const listPlayers = `-- name: ListPlayers :many
SELECT id, owner, player_name, position, team, drafted_at
FROM players
ORDER BY owner, player_name
`

type ListPlayersRow struct {
	ID         int64
	Owner      string
	PlayerName string
	Position   string
	Team       string
	DraftedAt  int32
}

func (q *Queries) ListPlayers(ctx context.Context) ([]ListPlayersRow, error) {
	rows, err := q.db.Query(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersRow
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.DraftedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
