// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rankings.sql

package db

import (
	"context"
)

const deleteRanking = `-- name: DeleteRanking :exec
DELETE FROM rankings
WHERE owner = $1 AND player_name = $2
`

type DeleteRankingParams struct {
	Owner      string
	PlayerName string
}

func (q *Queries) DeleteRanking(ctx context.Context, arg DeleteRankingParams) error {
	_, err := q.db.Exec(ctx, deleteRanking, arg.Owner, arg.PlayerName)
	return err
}

const deleteRankingsByOwner = `-- name: DeleteRankingsByOwner :exec
DELETE FROM rankings
WHERE owner = $1
`

func (q *Queries) DeleteRankingsByOwner(ctx context.Context, owner string) error {
	_, err := q.db.Exec(ctx, deleteRankingsByOwner, owner)
	return err
}

const insertRanking = `-- name: InsertRanking :exec
INSERT INTO rankings (owner, player_name, rank)
VALUES ($1, $2, $3)
`

type InsertRankingParams struct {
	Owner      string
	PlayerName string
	Rank       int32
}

func (q *Queries) InsertRanking(ctx context.Context, arg InsertRankingParams) error {
	_, err := q.db.Exec(ctx, insertRanking, arg.Owner, arg.PlayerName, arg.Rank)
	return err
}

const listRankings = `-- name: ListRankings :many
SELECT owner, player_name, rank
FROM rankings
ORDER BY owner, rank
`

type ListRankingsRow struct {
	Owner      string
	PlayerName string
	Rank       int32
}

func (q *Queries) ListRankings(ctx context.Context) ([]ListRankingsRow, error) {
	rows, err := q.db.Query(ctx, listRankings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRankingsRow
	for rows.Next() {
		var i ListRankingsRow
		if err := rows.Scan(&i.Owner, &i.PlayerName, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankingsByOwnerForUpdate = `-- name: ListRankingsByOwnerForUpdate :many
SELECT owner, player_name, rank
FROM rankings
WHERE owner = $1
ORDER BY rank
FOR UPDATE
`

type ListRankingsByOwnerForUpdateRow struct {
	Owner      string
	PlayerName string
	Rank       int32
}

func (q *Queries) ListRankingsByOwnerForUpdate(ctx context.Context, owner string) ([]ListRankingsByOwnerForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listRankingsByOwnerForUpdate, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRankingsByOwnerForUpdateRow
	for rows.Next() {
		var i ListRankingsByOwnerForUpdateRow
		if err := rows.Scan(&i.Owner, &i.PlayerName, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRankingRank = `-- name: UpdateRankingRank :exec
UPDATE rankings
SET rank = $3
WHERE owner = $1 AND player_name = $2
`

type UpdateRankingRankParams struct {
	Owner      string
	PlayerName string
	Rank       int32
}

func (q *Queries) UpdateRankingRank(ctx context.Context, arg UpdateRankingRankParams) error {
	_, err := q.db.Exec(ctx, updateRankingRank, arg.Owner, arg.PlayerName, arg.Rank)
	return err
}
