// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rankings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bigBoardConsensus = `-- name: BigBoardConsensus :many
WITH owner_totals AS (
    SELECT owner, COUNT(*) AS total
    FROM rankings
    GROUP BY owner
),
normalized AS (
    SELECT
        r.player_id,
        (r.rank::float8 / ot.total::float8)::float8 AS normalized_rank
    FROM rankings r
    JOIN owner_totals ot ON ot.owner = r.owner
)
SELECT
    p.id AS player_id,
    p.player_name,
    p.position,
    p.team,
    (AVG(n.normalized_rank))::float8 AS avg_normalized_rank,
    COUNT(*)::int AS num_owners_ranked
FROM normalized n
JOIN players p ON p.id = n.player_id
GROUP BY p.id, p.player_name, p.position, p.team
HAVING COUNT(*) >= 3
ORDER BY AVG(n.normalized_rank) ASC, p.player_name ASC
`

type BigBoardConsensusRow struct {
	PlayerID          int64
	PlayerName        string
	Position          string
	Team              string
	AvgNormalizedRank float64
	NumOwnersRanked   int32
}

// League-wide crowd-sourced big board (ai/08-consensus-and-analytics.md): the
// average of every owner's normalized overall rank (rank / their list size,
// 0.0 = best, 1.0 = worst) per player, so owners with different list sizes
// are comparable. Players ranked by fewer than 3 owners are excluded so the
// "consensus" is not one or two opinions.
func (q *Queries) BigBoardConsensus(ctx context.Context) ([]BigBoardConsensusRow, error) {
	rows, err := q.db.Query(ctx, bigBoardConsensus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BigBoardConsensusRow
	for rows.Next() {
		var i BigBoardConsensusRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.AvgNormalizedRank,
			&i.NumOwnersRanked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSnapshotRows = `-- name: CountSnapshotRows :one
SELECT COUNT(*)::int
FROM ranking_snapshots
WHERE taken_at = $1
`

func (q *Queries) CountSnapshotRows(ctx context.Context, takenAt pgtype.Timestamptz) (int32, error) {
	row := q.db.QueryRow(ctx, countSnapshotRows, takenAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteRanking = `-- name: DeleteRanking :exec
DELETE FROM rankings
WHERE owner = $1 AND player_id = $2
`

type DeleteRankingParams struct {
	Owner    string
	PlayerID int64
}

func (q *Queries) DeleteRanking(ctx context.Context, arg DeleteRankingParams) error {
	_, err := q.db.Exec(ctx, deleteRanking, arg.Owner, arg.PlayerID)
	return err
}

const deleteRankingsByOwner = `-- name: DeleteRankingsByOwner :exec
DELETE FROM rankings
WHERE owner = $1
`

func (q *Queries) DeleteRankingsByOwner(ctx context.Context, owner string) error {
	_, err := q.db.Exec(ctx, deleteRankingsByOwner, owner)
	return err
}

const getOwnerLatestSnapshotTakenAt = `-- name: GetOwnerLatestSnapshotTakenAt :one
SELECT MAX(taken_at)
FROM ranking_snapshots
WHERE owner = $1
`

func (q *Queries) GetOwnerLatestSnapshotTakenAt(ctx context.Context, owner string) (interface{}, error) {
	row := q.db.QueryRow(ctx, getOwnerLatestSnapshotTakenAt, owner)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const insertRanking = `-- name: InsertRanking :exec
INSERT INTO rankings (owner, player_id, rank)
VALUES ($1, $2, $3)
`

type InsertRankingParams struct {
	Owner    string
	PlayerID int64
	Rank     int32
}

func (q *Queries) InsertRanking(ctx context.Context, arg InsertRankingParams) error {
	_, err := q.db.Exec(ctx, insertRanking, arg.Owner, arg.PlayerID, arg.Rank)
	return err
}

const listDistinctPositions = `-- name: ListDistinctPositions :many
SELECT DISTINCT position
FROM players
ORDER BY position
`

func (q *Queries) ListDistinctPositions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var position string
		if err := rows.Scan(&position); err != nil {
			return nil, err
		}
		items = append(items, position)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerRankings = `-- name: ListOwnerRankings :many
SELECT player_id, rank
FROM rankings
WHERE owner = $1
ORDER BY rank
`

type ListOwnerRankingsRow struct {
	PlayerID int64
	Rank     int32
}

func (q *Queries) ListOwnerRankings(ctx context.Context, owner string) ([]ListOwnerRankingsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerRankings, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerRankingsRow
	for rows.Next() {
		var i ListOwnerRankingsRow
		if err := rows.Scan(&i.PlayerID, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerRankings = `-- name: ListPlayerRankings :many
WITH owner_totals AS (
    SELECT owner, COUNT(*) AS total
    FROM rankings
    GROUP BY owner
)
SELECT
    r.owner,
    r.rank AS overall_rank,
    RANK() OVER (PARTITION BY r.owner, p.position ORDER BY r.rank) AS positional_rank,
    ot.total AS owner_total,
    (r.rank::float8 / ot.total::float8)::float8 AS normalized_rank
FROM rankings r
JOIN players p ON p.id = r.player_id
JOIN owner_totals ot ON ot.owner = r.owner
WHERE r.player_id = $1
ORDER BY r.owner, r.rank
`

type ListPlayerRankingsRow struct {
	Owner          string
	OverallRank    int32
	PositionalRank int64
	OwnerTotal     int64
	NormalizedRank float64
}

func (q *Queries) ListPlayerRankings(ctx context.Context, playerID int64) ([]ListPlayerRankingsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerRankings, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerRankingsRow
	for rows.Next() {
		var i ListPlayerRankingsRow
		if err := rows.Scan(
			&i.Owner,
			&i.OverallRank,
			&i.PositionalRank,
			&i.OwnerTotal,
			&i.NormalizedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerSnapshotTrend = `-- name: ListPlayerSnapshotTrend :many
SELECT
    taken_at,
    (AVG((rank::float8 / owner_total::float8)))::float8 AS avg_normalized_rank
FROM ranking_snapshots
WHERE player_id = $1
GROUP BY taken_at
ORDER BY taken_at
`

type ListPlayerSnapshotTrendRow struct {
	TakenAt           pgtype.Timestamptz
	AvgNormalizedRank float64
}

func (q *Queries) ListPlayerSnapshotTrend(ctx context.Context, playerID int64) ([]ListPlayerSnapshotTrendRow, error) {
	rows, err := q.db.Query(ctx, listPlayerSnapshotTrend, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerSnapshotTrendRow
	for rows.Next() {
		var i ListPlayerSnapshotTrendRow
		if err := rows.Scan(&i.TakenAt, &i.AvgNormalizedRank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionalConsensus = `-- name: ListPositionalConsensus :many
WITH positioned AS (
    SELECT
        r.owner,
        r.player_id,
        p.position,
        RANK() OVER (PARTITION BY r.owner, p.position ORDER BY r.rank) AS positional_rank
    FROM rankings r
    JOIN players p ON p.id = r.player_id
)
SELECT
    p.id AS player_id,
    p.player_name,
    p.position,
    p.team,
    (AVG(pos.positional_rank))::float8 AS avg_positional_rank,
    COUNT(*) AS owner_count
FROM positioned pos
JOIN players p ON p.id = pos.player_id
WHERE p.position = ANY($1::text[])
GROUP BY p.id, p.player_name, p.position, p.team
ORDER BY AVG(pos.positional_rank) ASC, p.player_name ASC
`

type ListPositionalConsensusRow struct {
	PlayerID          int64
	PlayerName        string
	Position          string
	Team              string
	AvgPositionalRank float64
	OwnerCount        int64
}

// League-wide crowd-sourced positional big board: the average positional
// rank per player across every owner who ranked them.
func (q *Queries) ListPositionalConsensus(ctx context.Context, positions []string) ([]ListPositionalConsensusRow, error) {
	rows, err := q.db.Query(ctx, listPositionalConsensus, positions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPositionalConsensusRow
	for rows.Next() {
		var i ListPositionalConsensusRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.AvgPositionalRank,
			&i.OwnerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankingsByOwnerForUpdate = `-- name: ListRankingsByOwnerForUpdate :many
SELECT r.owner, p.id AS player_id, p.player_name, p.position, p.team, r.rank
FROM rankings r
JOIN players p ON p.id = r.player_id
WHERE r.owner = $1
ORDER BY r.rank
FOR UPDATE
`

type ListRankingsByOwnerForUpdateRow struct {
	Owner      string
	PlayerID   int64
	PlayerName string
	Position   string
	Team       string
	Rank       int32
}

func (q *Queries) ListRankingsByOwnerForUpdate(ctx context.Context, owner string) ([]ListRankingsByOwnerForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listRankingsByOwnerForUpdate, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRankingsByOwnerForUpdateRow
	for rows.Next() {
		var i ListRankingsByOwnerForUpdateRow
		if err := rows.Scan(
			&i.Owner,
			&i.PlayerID,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankingsWithPositionalRank = `-- name: ListRankingsWithPositionalRank :many
SELECT
    r.owner,
    p.id AS player_id,
    p.player_name,
    p.position,
    p.team,
    r.rank AS overall_rank,
    RANK() OVER (PARTITION BY r.owner, p.position ORDER BY r.rank) AS positional_rank
FROM rankings r
JOIN players p ON p.id = r.player_id
ORDER BY r.owner, r.rank
`

type ListRankingsWithPositionalRankRow struct {
	Owner          string
	PlayerID       int64
	PlayerName     string
	Position       string
	Team           string
	OverallRank    int32
	PositionalRank int64
}

// Positional rank is derived, not stored: the player's rank within their
// position, computed at query time from the overall (big-board) order.
// RANK() (not DENSE_RANK) so future ties read like a draft board (1,1,3).
func (q *Queries) ListRankingsWithPositionalRank(ctx context.Context) ([]ListRankingsWithPositionalRankRow, error) {
	rows, err := q.db.Query(ctx, listRankingsWithPositionalRank)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRankingsWithPositionalRankRow
	for rows.Next() {
		var i ListRankingsWithPositionalRankRow
		if err := rows.Scan(
			&i.Owner,
			&i.PlayerID,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.OverallRank,
			&i.PositionalRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankingsWithPositionalRankFiltered = `-- name: ListRankingsWithPositionalRankFiltered :many
SELECT
    r.owner,
    p.id AS player_id,
    p.player_name,
    p.position,
    p.team,
    r.rank AS overall_rank,
    RANK() OVER (PARTITION BY r.owner, p.position ORDER BY r.rank) AS positional_rank
FROM rankings r
JOIN players p ON p.id = r.player_id
WHERE p.position = ANY($1::text[])
ORDER BY r.owner, r.rank
`

type ListRankingsWithPositionalRankFilteredRow struct {
	Owner          string
	PlayerID       int64
	PlayerName     string
	Position       string
	Team           string
	OverallRank    int32
	PositionalRank int64
}

func (q *Queries) ListRankingsWithPositionalRankFiltered(ctx context.Context, positions []string) ([]ListRankingsWithPositionalRankFilteredRow, error) {
	rows, err := q.db.Query(ctx, listRankingsWithPositionalRankFiltered, positions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRankingsWithPositionalRankFilteredRow
	for rows.Next() {
		var i ListRankingsWithPositionalRankFilteredRow
		if err := rows.Scan(
			&i.Owner,
			&i.PlayerID,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.OverallRank,
			&i.PositionalRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotRanksForOwner = `-- name: ListSnapshotRanksForOwner :many
SELECT player_id, rank
FROM ranking_snapshots
WHERE owner = $1 AND taken_at = $2
`

type ListSnapshotRanksForOwnerParams struct {
	Owner   string
	TakenAt pgtype.Timestamptz
}

type ListSnapshotRanksForOwnerRow struct {
	PlayerID int64
	Rank     int32
}

func (q *Queries) ListSnapshotRanksForOwner(ctx context.Context, arg ListSnapshotRanksForOwnerParams) ([]ListSnapshotRanksForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listSnapshotRanksForOwner, arg.Owner, arg.TakenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnapshotRanksForOwnerRow
	for rows.Next() {
		var i ListSnapshotRanksForOwnerRow
		if err := rows.Scan(&i.PlayerID, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotCurrentRankings = `-- name: SnapshotCurrentRankings :exec
WITH owner_totals AS (
    SELECT owner, COUNT(*) AS total
    FROM rankings
    GROUP BY owner
)
INSERT INTO ranking_snapshots (taken_at, owner, player_id, rank, owner_total)
SELECT $1, r.owner, r.player_id, r.rank, ot.total
FROM rankings r
JOIN owner_totals ot ON ot.owner = r.owner
`

func (q *Queries) SnapshotCurrentRankings(ctx context.Context, takenAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, snapshotCurrentRankings, takenAt)
	return err
}

const updateRankingRank = `-- name: UpdateRankingRank :exec
UPDATE rankings
SET rank = $3
WHERE owner = $1 AND player_id = $2
`

type UpdateRankingRankParams struct {
	Owner    string
	PlayerID int64
	Rank     int32
}

func (q *Queries) UpdateRankingRank(ctx context.Context, arg UpdateRankingRankParams) error {
	_, err := q.db.Exec(ctx, updateRankingRank, arg.Owner, arg.PlayerID, arg.Rank)
	return err
}
