// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastSuccessfulSync = `-- name: GetLastSuccessfulSync :one
SELECT finished_at
FROM sync_log
WHERE status = 'success'
ORDER BY started_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulSync(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastSuccessfulSync)
	var finished_at pgtype.Timestamptz
	err := row.Scan(&finished_at)
	return finished_at, err
}

const getLatestSyncLog = `-- name: GetLatestSyncLog :one
SELECT id, started_at, finished_at, source, status, message, inserted, updated, deleted, unchanged, delete_skipped_count
FROM sync_log
ORDER BY started_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncLog(ctx context.Context) (SyncLog, error) {
	row := q.db.QueryRow(ctx, getLatestSyncLog)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Source,
		&i.Status,
		&i.Message,
		&i.Inserted,
		&i.Updated,
		&i.Deleted,
		&i.Unchanged,
		&i.DeleteSkippedCount,
	)
	return i, err
}

const insertSyncLog = `-- name: InsertSyncLog :one
INSERT INTO sync_log (
    started_at, finished_at, source, status, message,
    inserted, updated, deleted, unchanged, delete_skipped_count
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, started_at, finished_at, source, status, message, inserted, updated, deleted, unchanged, delete_skipped_count
`

type InsertSyncLogParams struct {
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
	Source             string
	Status             string
	Message            pgtype.Text
	Inserted           int32
	Updated            int32
	Deleted            int32
	Unchanged          int32
	DeleteSkippedCount int32
}

func (q *Queries) InsertSyncLog(ctx context.Context, arg InsertSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRow(ctx, insertSyncLog,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Source,
		arg.Status,
		arg.Message,
		arg.Inserted,
		arg.Updated,
		arg.Deleted,
		arg.Unchanged,
		arg.DeleteSkippedCount,
	)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Source,
		&i.Status,
		&i.Message,
		&i.Inserted,
		&i.Updated,
		&i.Deleted,
		&i.Unchanged,
		&i.DeleteSkippedCount,
	)
	return i, err
}

const listRecentSyncLog = `-- name: ListRecentSyncLog :many
SELECT id, started_at, finished_at, source, status, message, inserted, updated, deleted, unchanged, delete_skipped_count
FROM sync_log
ORDER BY started_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListRecentSyncLog(ctx context.Context, limit int32) ([]SyncLog, error) {
	rows, err := q.db.Query(ctx, listRecentSyncLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncLog
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Source,
			&i.Status,
			&i.Message,
			&i.Inserted,
			&i.Updated,
			&i.Deleted,
			&i.Unchanged,
			&i.DeleteSkippedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
