// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tiers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTierBreaksForScope = `-- name: DeleteTierBreaksForScope :exec
DELETE FROM tier_breaks
WHERE owner = $1 AND position = $2
`

type DeleteTierBreaksForScopeParams struct {
	Owner    string
	Position string
}

func (q *Queries) DeleteTierBreaksForScope(ctx context.Context, arg DeleteTierBreaksForScopeParams) error {
	_, err := q.db.Exec(ctx, deleteTierBreaksForScope, arg.Owner, arg.Position)
	return err
}

const insertTierBreak = `-- name: InsertTierBreak :exec
INSERT INTO tier_breaks (owner, position, before_rank, label)
VALUES ($1, $2, $3, $4)
`

type InsertTierBreakParams struct {
	Owner      string
	Position   string
	BeforeRank int32
	Label      pgtype.Text
}

func (q *Queries) InsertTierBreak(ctx context.Context, arg InsertTierBreakParams) error {
	_, err := q.db.Exec(ctx, insertTierBreak,
		arg.Owner,
		arg.Position,
		arg.BeforeRank,
		arg.Label,
	)
	return err
}

const listTierBreaks = `-- name: ListTierBreaks :many
SELECT position, before_rank, label
FROM tier_breaks
WHERE owner = $1
ORDER BY position, before_rank
`

type ListTierBreaksRow struct {
	Position   string
	BeforeRank int32
	Label      pgtype.Text
}

func (q *Queries) ListTierBreaks(ctx context.Context, owner string) ([]ListTierBreaksRow, error) {
	rows, err := q.db.Query(ctx, listTierBreaks, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTierBreaksRow
	for rows.Next() {
		var i ListTierBreaksRow
		if err := rows.Scan(&i.Position, &i.BeforeRank, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTierBreaksAllOwners = `-- name: ListTierBreaksAllOwners :many
SELECT owner, position, before_rank, label
FROM tier_breaks
ORDER BY owner, position, before_rank
`

type ListTierBreaksAllOwnersRow struct {
	Owner      string
	Position   string
	BeforeRank int32
	Label      pgtype.Text
}

func (q *Queries) ListTierBreaksAllOwners(ctx context.Context) ([]ListTierBreaksAllOwnersRow, error) {
	rows, err := q.db.Query(ctx, listTierBreaksAllOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTierBreaksAllOwnersRow
	for rows.Next() {
		var i ListTierBreaksAllOwnersRow
		if err := rows.Scan(
			&i.Owner,
			&i.Position,
			&i.BeforeRank,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
