// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trade_suggestions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDraftedPlayers = `-- name: ListDraftedPlayers :many
SELECT id, player_name, position, team, drafted_by_username
FROM players
WHERE drafted_by_username IS NOT NULL
ORDER BY id
`

type ListDraftedPlayersRow struct {
	ID                int64
	PlayerName        string
	Position          string
	Team              string
	DraftedByUsername pgtype.Text
}

// Players linked to an owner via the draft, for ownership checks in
// pairwise trade suggestions.
func (q *Queries) ListDraftedPlayers(ctx context.Context) ([]ListDraftedPlayersRow, error) {
	rows, err := q.db.Query(ctx, listDraftedPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftedPlayersRow
	for rows.Next() {
		var i ListDraftedPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.DraftedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExcludedOwners = `-- name: ListExcludedOwners :many
SELECT owner
FROM (
    SELECT owner, COUNT(*) AS total
    FROM rankings
    GROUP BY owner
) e
WHERE e.total < $1::int
ORDER BY owner
`

// Owners present in rankings but below the min_ranked_players threshold,
// surfaced in responses so the exclusion is visible rather than silent.
func (q *Queries) ListExcludedOwners(ctx context.Context, minRankedPlayers int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listExcludedOwners, minRankedPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var owner string
		if err := rows.Scan(&owner); err != nil {
			return nil, err
		}
		items = append(items, owner)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNormalizedRankings = `-- name: ListNormalizedRankings :many
SELECT
    r.owner,
    r.player_id,
    r.rank,
    ot.total,
    (r.rank::float8 / ot.total::float8)::float8 AS normalized_rank
FROM rankings r
JOIN (
    SELECT owner, COUNT(*) AS total
    FROM rankings
    GROUP BY owner
    HAVING COUNT(*) >= $1::int
) ot ON ot.owner = r.owner
ORDER BY r.owner, r.rank
`

type ListNormalizedRankingsRow struct {
	Owner          string
	PlayerID       int64
	Rank           int32
	Total          int64
	NormalizedRank float64
}

// Every (owner, player) rank with the owner's list size, restricted to owners
// who ranked at least min_ranked_players players. normalized_rank = rank / total
// (0.0 = best, 1.0 = worst) so owners with different list sizes are comparable.
func (q *Queries) ListNormalizedRankings(ctx context.Context, minRankedPlayers int32) ([]ListNormalizedRankingsRow, error) {
	rows, err := q.db.Query(ctx, listNormalizedRankings, minRankedPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNormalizedRankingsRow
	for rows.Next() {
		var i ListNormalizedRankingsRow
		if err := rows.Scan(
			&i.Owner,
			&i.PlayerID,
			&i.Rank,
			&i.Total,
			&i.NormalizedRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playerDisagreement = `-- name: PlayerDisagreement :many
WITH owner_totals AS (
    SELECT owner, COUNT(*) AS total
    FROM rankings
    GROUP BY owner
    HAVING COUNT(*) >= $2::int
),
ranked AS (
    SELECT
        r.owner,
        r.player_id,
        (r.rank::float8 / ot.total::float8)::float8 AS normalized_rank
    FROM rankings r
    JOIN owner_totals ot ON ot.owner = r.owner
)
SELECT
    p.id AS player_id,
    p.player_name,
    p.position,
    p.team,
    COUNT(*)::int AS num_owners_ranked,
    MIN(rk.normalized_rank)::float8 AS best_normalized_rank,
    MAX(rk.normalized_rank)::float8 AS worst_normalized_rank,
    (MAX(rk.normalized_rank) - MIN(rk.normalized_rank))::float8 AS disagreement_spread,
    (array_agg(rk.owner ORDER BY rk.normalized_rank, rk.owner))[1]::text AS highest_rater,
    (array_agg(rk.owner ORDER BY rk.normalized_rank DESC, rk.owner))[1]::text AS lowest_rater
FROM ranked rk
JOIN players p ON p.id = rk.player_id
GROUP BY p.id, p.player_name, p.position, p.team
HAVING COUNT(*) >= 2
ORDER BY disagreement_spread DESC, p.player_name ASC
LIMIT $1::int
`

type PlayerDisagreementParams struct {
	RowLimit         int32
	MinRankedPlayers int32
}

type PlayerDisagreementRow struct {
	PlayerID            int64
	PlayerName          string
	Position            string
	Team                string
	NumOwnersRanked     int32
	BestNormalizedRank  float64
	WorstNormalizedRank float64
	DisagreementSpread  float64
	HighestRater        string
	LowestRater         string
}

// Disagreement leaderboard: players ranked by at least two qualifying owners,
// spread = max(normalized_rank) - min(normalized_rank). Ties on spread break
// by player name for stable output.
func (q *Queries) PlayerDisagreement(ctx context.Context, arg PlayerDisagreementParams) ([]PlayerDisagreementRow, error) {
	rows, err := q.db.Query(ctx, playerDisagreement, arg.RowLimit, arg.MinRankedPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerDisagreementRow
	for rows.Next() {
		var i PlayerDisagreementRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.PlayerName,
			&i.Position,
			&i.Team,
			&i.NumOwnersRanked,
			&i.BestNormalizedRank,
			&i.WorstNormalizedRank,
			&i.DisagreementSpread,
			&i.HighestRater,
			&i.LowestRater,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
